name: Workflow Blog Post

jobs:
  update-readme-with-blog:
    name: Update README with Last Blog Post
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://themonthlyfreelancer.substack.com/feed/,https://mbesson.github.io/index.xml"

