name: GitHub - Activity - Readme

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.PROFILE_TOKEN }}
        with:
          COMMIT_MSG: '[ACTIONS]: Checked your most recent activity'
          MAX_LINES: 5
